---

- name: Create web root directory
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Check if WordPress already downloaded
  ansible.builtin.stat:
    path: /tmp/wordpress.tar.gz
  register: wp_archive

- name: Download WordPress
  ansible.builtin.get_url:
    url: "{{ wp_download_url }}"
    dest: /tmp/wordpress.tar.gz
  when: not wp_archive.stat.exists

- name: Extract WordPress (only if WordPress not already extracted)
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ install_dir }}"
    remote_src: yes
    creates: "{{ install_dir }}/wp-settings.php"

- name: Copy wp-config template
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ install_dir }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0644'
