---
galaxy_info:
  author: "Your Name"
  description: "Firewall role to configure UFW or FirewallD depending on OS"
  company: "N/A"
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: CentOS
      versions:
        - all
    - name: AlmaLinux
      versions:
        - all